/********************************************************************
* EclFrameDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EclFrameDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEclFrameDict();
extern void G__cpp_setup_inheritanceEclFrameDict();
extern void G__cpp_setup_typetableEclFrameDict();
extern void G__cpp_setup_memvarEclFrameDict();
extern void G__cpp_setup_globalEclFrameDict();
extern void G__cpp_setup_memfuncEclFrameDict();
extern void G__cpp_setup_funcEclFrameDict();
extern void G__set_cpp_environmentEclFrameDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EclFrame.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EclFrameDictLN_TClass;
extern G__linked_taginfo G__EclFrameDictLN_TBuffer;
extern G__linked_taginfo G__EclFrameDictLN_TMemberInspector;
extern G__linked_taginfo G__EclFrameDictLN_TObject;
extern G__linked_taginfo G__EclFrameDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__EclFrameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EclFrameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EclFrameDictLN_TQObject;
extern G__linked_taginfo G__EclFrameDictLN_TGWindow;
extern G__linked_taginfo G__EclFrameDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EclFrameDictLN_TGObject;
extern G__linked_taginfo G__EclFrameDictLN_TGFrame;
extern G__linked_taginfo G__EclFrameDictLN_TGCompositeFrame;
extern G__linked_taginfo G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EclFrameDictLN_TGTextButton;
extern G__linked_taginfo G__EclFrameDictLN_TGVerticalFrame;
extern G__linked_taginfo G__EclFrameDictLN_TGMainFrame;
extern G__linked_taginfo G__EclFrameDictLN_TGGroupFrame;
extern G__linked_taginfo G__EclFrameDictLN_TGCheckButton;
extern G__linked_taginfo G__EclFrameDictLN_TGDoubleHSlider;
extern G__linked_taginfo G__EclFrameDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__EclFrameDictLN_TGNumberEntry;
extern G__linked_taginfo G__EclFrameDictLN_TGListTreeItem;
extern G__linked_taginfo G__EclFrameDictLN_TGListTree;
extern G__linked_taginfo G__EclFrameDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR;
extern G__linked_taginfo G__EclFrameDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR;
extern G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EclFrameDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EclFrameDictLN_Belle2;
extern G__linked_taginfo G__EclFrameDictLN_Belle2cLcLECLChannelMapper;
extern G__linked_taginfo G__EclFrameDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EclFrameDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EclFrameDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EclFrameDictLN_Belle2cLcLEclData;
extern G__linked_taginfo G__EclFrameDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EclFrameDictLN_Belle2cLcLEclDatacLcLEclSubsystem;
extern G__linked_taginfo G__EclFrameDictLN_Belle2cLcLMultilineWidget;
extern G__linked_taginfo G__EclFrameDictLN_vectorlETGLabelmUcOallocatorlETGLabelmUgRsPgR;
extern G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlETGLabelmUcOallocatorlETGLabelmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EclFrameDictLN_Belle2cLcLEclPainter;
extern G__linked_taginfo G__EclFrameDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EclFrameDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EclFrameDictLN_Belle2cLcLEclPainterType;
extern G__linked_taginfo G__EclFrameDictLN_Belle2cLcLEclFrame;
extern G__linked_taginfo G__EclFrameDictLN_Belle2cLcLEclFramecLcLEclFrameCommandIdentifiers;

/* STUB derived class for protected member access */
