//
// File generated by rootcint at Wed Jun  3 10:56:49 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME EclFrameDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "EclFrameDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void EclFrame_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_EclFrame(void *p);
   static void deleteArray_EclFrame(void *p);
   static void destruct_EclFrame(void *p);
   static void streamer_EclFrame(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::EclFrame*)
   {
      ::EclFrame *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::EclFrame >(0);
      static ::ROOT::TGenericClassInfo 
         instance("EclFrame", ::EclFrame::Class_Version(), "./EclFrame.h", 26,
                  typeid(::EclFrame), DefineBehavior(ptr, ptr),
                  &::EclFrame::Dictionary, isa_proxy, 0,
                  sizeof(::EclFrame) );
      instance.SetDelete(&delete_EclFrame);
      instance.SetDeleteArray(&deleteArray_EclFrame);
      instance.SetDestructor(&destruct_EclFrame);
      instance.SetStreamerFunc(&streamer_EclFrame);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::EclFrame*)
   {
      return GenerateInitInstanceLocal((::EclFrame*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::EclFrame*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr EclFrame::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *EclFrame::Class_Name()
{
   return "EclFrame";
}

//______________________________________________________________________________
const char *EclFrame::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::EclFrame*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int EclFrame::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::EclFrame*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void EclFrame::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::EclFrame*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *EclFrame::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::EclFrame*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void EclFrame::Streamer(TBuffer &R__b)
{
   // Stream an object of class EclFrame.

   TGMainFrame::Streamer(R__b);
}

//______________________________________________________________________________
void EclFrame::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class EclFrame.
      TClass *R__cl = ::EclFrame::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_settings", &m_settings);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_frame1", &m_frame1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_frame2", &m_frame2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_frame3", &m_frame3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_list_tree", &m_list_tree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_frame4", &m_frame4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_frame5", &m_frame5);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_draw", &m_draw);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_ecanvas", &m_ecanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_glviewer", &m_glviewer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_gl_view", &m_gl_view);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_painter_type", &m_painter_type);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_ecl_data", &m_ecl_data);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_time_slider", &m_time_slider);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_ev_slider", &m_ev_slider);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_events_max", &m_events_max);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_events_min", &m_events_min);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_channel_id", &m_channel_id);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_min_en_threshold", &m_min_en_threshold);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_max_en_threshold", &m_max_en_threshold);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_threshold_switch", &m_threshold_switch);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_ecl_painter", &m_ecl_painter);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_EclFrame(void *p) {
      delete ((::EclFrame*)p);
   }
   static void deleteArray_EclFrame(void *p) {
      delete [] ((::EclFrame*)p);
   }
   static void destruct_EclFrame(void *p) {
      typedef ::EclFrame current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_EclFrame(TBuffer &buf, void *obj) {
      ((::EclFrame*)obj)->::EclFrame::Streamer(buf);
   }
} // end of namespace ROOT for class ::EclFrame

/********************************************************
* EclFrameDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableEclFrameDict();

extern "C" void G__set_cpp_environmentEclFrameDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("EclFrame.h");
  G__cpp_reset_tagtableEclFrameDict();
}
#include <new>
extern "C" int G__cpp_dllrevEclFrameDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* EclFrame */
static int G__EclFrameDict_1068_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EclFrame* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EclFrame(
(TGWindow*) G__int(libp->para[0]), (EclData*) G__int(libp->para[1])
, (bool) G__int(libp->para[2]));
     } else {
       p = new((void*) gvp) EclFrame(
(TGWindow*) G__int(libp->para[0]), (EclData*) G__int(libp->para[1])
, (bool) G__int(libp->para[2]));
     }
     break;
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EclFrame((TGWindow*) G__int(libp->para[0]), (EclData*) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) EclFrame((TGWindow*) G__int(libp->para[0]), (EclData*) G__int(libp->para[1]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EclFrameDictLN_EclFrame));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EclFrame*) G__getstructoffset())->UpdateEventRange();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EclFrame*) G__getstructoffset())->ShowPrevEvents();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EclFrame*) G__getstructoffset())->ShowNextEvents();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EclFrame*) G__getstructoffset())->ExcludeChannel();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EclFrame*) G__getstructoffset())->DoDraw();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EclFrame*) G__getstructoffset())->UpdateInfo((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (TObject*) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EclFrame*) G__getstructoffset())->UpdateInfo3D((TObject*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EclFrame*) G__getstructoffset())->ChangeRange((TGListTreeItem*) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((EclFrame*) G__getstructoffset())->ChangeType((int) G__int(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((EclFrame*) G__getstructoffset())->ChangeType((int) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) EclFrame::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EclFrame::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) EclFrame::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EclFrame::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EclFrame*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EclFrame::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EclFrame::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EclFrame::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_1068_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EclFrame::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef EclFrame G__TEclFrame;
static int G__EclFrameDict_1068_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (EclFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((EclFrame*) (soff+(sizeof(EclFrame)*i)))->~G__TEclFrame();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (EclFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((EclFrame*) (soff))->~G__TEclFrame();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* EclFrame */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncEclFrameDict {
 public:
  G__Sizep2memfuncEclFrameDict(): p(&G__Sizep2memfuncEclFrameDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncEclFrameDict::*p)();
};

size_t G__get_sizep2memfuncEclFrameDict()
{
  G__Sizep2memfuncEclFrameDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceEclFrameDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__EclFrameDictLN_EclFrame))) {
     EclFrame *G__Lderived;
     G__Lderived=(EclFrame*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EclFrameDictLN_EclFrame),G__get_linked_tagnum(&G__EclFrameDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EclFrameDictLN_EclFrame),G__get_linked_tagnum(&G__EclFrameDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EclFrameDictLN_EclFrame),G__get_linked_tagnum(&G__EclFrameDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EclFrameDictLN_EclFrame),G__get_linked_tagnum(&G__EclFrameDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EclFrameDictLN_EclFrame),G__get_linked_tagnum(&G__EclFrameDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EclFrameDictLN_EclFrame),G__get_linked_tagnum(&G__EclFrameDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EclFrameDictLN_EclFrame),G__get_linked_tagnum(&G__EclFrameDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableEclFrameDict() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGLabel*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGLabelmUcOallocatorlETGLabelmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGLabelmUcOallocatorlETGLabelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGLabelmUcOallocatorlETGLabelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGLabelmUcOallocatorlETGLabelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGLabelmUcOallocatorlETGLabelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Int_t,TGeoElementRN*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGeoElementRN*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGeoElementRN*,less<int> >",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ThreadData_t*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGeoVolumeAssembly::ThreadData_t*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Long_t,TGeoNavigatorArray*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<long,TGeoNavigatorArray*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<long,TGeoNavigatorArray*,less<long> >",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Long_t,Int_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGLPlane>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGLPlanecOallocatorlETGLPlanegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGLPlanecOallocatorlETGLPlanegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGLPlanecOallocatorlETGLPlanegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGLPlanecOallocatorlETGLPlanegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGLPlanecOallocatorlETGLPlanegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<Bool_t,TGLLine3>",117,G__get_linked_tagnum(&G__EclFrameDictLN_pairlEboolcOTGLLine3gR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<Bool_t,TGLVertex3>",117,G__get_linked_tagnum(&G__EclFrameDictLN_pairlEboolcOTGLVertex3gR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UChar_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<Int_t,Int_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_pairlEintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<Double_t,Double_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_pairlEdoublecOdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<TGLOverlayElement*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_listlETGLOverlayElementmUcOallocatorlETGLOverlayElementmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<TGLSceneInfo*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_listlETGLSceneInfomUcOallocatorlETGLSceneInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGLSceneInfo*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGLSceneInfomUcOallocatorlETGLSceneInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGLSceneInfomUcOallocatorlETGLSceneInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGLSceneInfomUcOallocatorlETGLSceneInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGLSceneInfomUcOallocatorlETGLSceneInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGLSceneInfomUcOallocatorlETGLSceneInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGLOverlayElement*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGLOverlayElementmUcOallocatorlETGLOverlayElementmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGLOverlayElementmUcOallocatorlETGLOverlayElementmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGLOverlayElementmUcOallocatorlETGLOverlayElementmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGLOverlayElementmUcOallocatorlETGLOverlayElementmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGLOverlayElementmUcOallocatorlETGLOverlayElementmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<TGLColorSet*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_listlETGLColorSetmUcOallocatorlETGLColorSetmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* EclFrame */
static void G__setup_memvarEclFrame(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EclFrameDictLN_EclFrame));
   { EclFrame *p; p=(EclFrame*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGVerticalFrame),-1,-1,4,"m_settings=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_MultilineWidget),-1,-1,4,"m_frame1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGGroupFrame),-1,-1,4,"m_frame2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGGroupFrame),-1,-1,4,"m_frame3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGListTree),-1,-1,4,"m_list_tree=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGGroupFrame),-1,-1,4,"m_frame4=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGGroupFrame),-1,-1,4,"m_frame5=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGTextButton),-1,-1,4,"m_draw=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TRootEmbeddedCanvas),-1,-1,4,"m_ecanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGLSAViewer),-1,-1,4,"m_glviewer=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_gl_view=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_EclPainterType),-1,-1,4,"m_painter_type=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_EclData),-1,-1,4,"m_ecl_data=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGDoubleHSlider),-1,-1,4,"m_time_slider=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGDoubleHSlider),-1,-1,4,"m_ev_slider=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGNumberEntry),-1,-1,4,"m_events_max=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGNumberEntry),-1,-1,4,"m_events_min=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGNumberEntry),-1,-1,4,"m_channel_id=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGNumberEntry),-1,-1,4,"m_min_en_threshold=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGNumberEntry),-1,-1,4,"m_max_en_threshold=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGCheckButton),-1,-1,4,"m_threshold_switch=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_EclPainter),-1,-1,4,"m_ecl_painter=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarEclFrameDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncEclFrame(void) {
   /* EclFrame */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EclFrameDictLN_EclFrame));
   G__memfunc_setup("EclFrame",767,G__EclFrameDict_1068_0_1, 105, G__get_linked_tagnum(&G__EclFrameDictLN_EclFrame), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p U 'EclData' - 0 - data "
"g - - 0 'false' gl_view", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitGUI",633,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 3, 1, 4, 0, 
"i - - 0 - w i - - 0 - h "
"g - - 0 - gl_view", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitData",782,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MapSubwindows",1363,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetGLViewMode",1247,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 4, 0, 
"g - - 0 - mode g - - 0 'false' request_update", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateEventRange",1618,G__EclFrameDict_1068_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ShowPrevEvents",1459,G__EclFrameDict_1068_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ShowNextEvents",1461,G__EclFrameDict_1068_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ExcludeChannel",1411,G__EclFrameDict_1068_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoDraw",577,G__EclFrameDict_1068_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateInfo",1007,G__EclFrameDict_1068_0_11, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - event i - - 0 - px "
"i - - 0 - py U 'TObject' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateInfo3D",1126,G__EclFrameDict_1068_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TObject' - 0 - obj h - 'UInt_t' 0 - state", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangeRange",1075,G__EclFrameDict_1068_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TGListTreeItem' - 0 - entry i - - 0 - btn", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangeType",1000,G__EclFrameDict_1068_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - type g - - 0 'true' redraw", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__EclFrameDict_1068_0_15, 85, G__get_linked_tagnum(&G__EclFrameDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&EclFrame::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__EclFrameDict_1068_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EclFrame::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__EclFrameDict_1068_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&EclFrame::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__EclFrameDict_1068_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&EclFrame::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__EclFrameDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__EclFrameDict_1068_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__EclFrameDict_1068_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EclFrame::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__EclFrameDict_1068_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EclFrame::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__EclFrameDict_1068_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EclFrame::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__EclFrameDict_1068_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EclFrame::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~EclFrame", 893, G__EclFrameDict_1068_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncEclFrameDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
}

static void G__cpp_setup_global9() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalEclFrameDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
  G__cpp_setup_global9();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcEclFrameDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__EclFrameDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR = { "vector<unsigned char,allocator<unsigned char> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGVerticalFrame = { "TGVerticalFrame" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGGroupFrame = { "TGGroupFrame" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGCheckButton = { "TGCheckButton" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGDoubleHSlider = { "TGDoubleHSlider" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGNumberEntry = { "TGNumberEntry" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGListTreeItem = { "TGListTreeItem" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGListTree = { "TGListTree" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_pairlEintcOintgR = { "pair<int,int>" , 115 , -1 };
G__linked_taginfo G__EclFrameDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR = { "map<long,int,less<long>,allocator<pair<const long,int> > >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_pairlEdoublecOdoublegR = { "pair<double,double>" , 115 , -1 };
G__linked_taginfo G__EclFrameDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_EclData = { "EclData" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_MultilineWidget = { "MultilineWidget" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlETGLabelmUcOallocatorlETGLabelmUgRsPgR = { "vector<TGLabel*,allocator<TGLabel*> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlETGLabelmUcOallocatorlETGLabelmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGLabel*,allocator<TGLabel*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_EclPainter = { "EclPainter" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR = { "map<int,TGeoElementRN*,less<int>,allocator<pair<const int,TGeoElementRN*> > >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR = { "vector<TGeoVolumeAssembly::ThreadData_t*,allocator<TGeoVolumeAssembly::ThreadData_t*> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGeoVolumeAssembly::ThreadData_t*,allocator<TGeoVolumeAssembly::ThreadData_t*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR = { "map<long,TGeoNavigatorArray*,less<long>,allocator<pair<const long,TGeoNavigatorArray*> > >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_EclPainterType = { "EclPainterType" , 101 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlETGLPlanecOallocatorlETGLPlanegRsPgR = { "vector<TGLPlane,allocator<TGLPlane> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlETGLPlanecOallocatorlETGLPlanegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGLPlane,allocator<TGLPlane> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_pairlEboolcOTGLLine3gR = { "pair<bool,TGLLine3>" , 115 , -1 };
G__linked_taginfo G__EclFrameDictLN_pairlEboolcOTGLVertex3gR = { "pair<bool,TGLVertex3>" , 115 , -1 };
G__linked_taginfo G__EclFrameDictLN_listlETGLOverlayElementmUcOallocatorlETGLOverlayElementmUgRsPgR = { "list<TGLOverlayElement*,allocator<TGLOverlayElement*> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_listlETGLSceneInfomUcOallocatorlETGLSceneInfomUgRsPgR = { "list<TGLSceneInfo*,allocator<TGLSceneInfo*> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlETGLSceneInfomUcOallocatorlETGLSceneInfomUgRsPgR = { "vector<TGLSceneInfo*,allocator<TGLSceneInfo*> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlETGLSceneInfomUcOallocatorlETGLSceneInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGLSceneInfo*,allocator<TGLSceneInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlETGLOverlayElementmUcOallocatorlETGLOverlayElementmUgRsPgR = { "vector<TGLOverlayElement*,allocator<TGLOverlayElement*> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlETGLOverlayElementmUcOallocatorlETGLOverlayElementmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGLOverlayElement*,allocator<TGLOverlayElement*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_listlETGLColorSetmUcOallocatorlETGLColorSetmUgRsPgR = { "list<TGLColorSet*,allocator<TGLColorSet*> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGLSAViewer = { "TGLSAViewer" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_EclFrame = { "EclFrame" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableEclFrameDict() {
  G__EclFrameDictLN_TClass.tagnum = -1 ;
  G__EclFrameDictLN_TBuffer.tagnum = -1 ;
  G__EclFrameDictLN_TMemberInspector.tagnum = -1 ;
  G__EclFrameDictLN_TObject.tagnum = -1 ;
  G__EclFrameDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_TQObject.tagnum = -1 ;
  G__EclFrameDictLN_TGWindow.tagnum = -1 ;
  G__EclFrameDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_TGObject.tagnum = -1 ;
  G__EclFrameDictLN_TGFrame.tagnum = -1 ;
  G__EclFrameDictLN_TGCompositeFrame.tagnum = -1 ;
  G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__EclFrameDictLN_TGTextButton.tagnum = -1 ;
  G__EclFrameDictLN_TGVerticalFrame.tagnum = -1 ;
  G__EclFrameDictLN_TGMainFrame.tagnum = -1 ;
  G__EclFrameDictLN_TGGroupFrame.tagnum = -1 ;
  G__EclFrameDictLN_TGCheckButton.tagnum = -1 ;
  G__EclFrameDictLN_TGDoubleHSlider.tagnum = -1 ;
  G__EclFrameDictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__EclFrameDictLN_TGNumberEntry.tagnum = -1 ;
  G__EclFrameDictLN_TGListTreeItem.tagnum = -1 ;
  G__EclFrameDictLN_TGListTree.tagnum = -1 ;
  G__EclFrameDictLN_pairlEintcOintgR.tagnum = -1 ;
  G__EclFrameDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_pairlEdoublecOdoublegR.tagnum = -1 ;
  G__EclFrameDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_EclData.tagnum = -1 ;
  G__EclFrameDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__EclFrameDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__EclFrameDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__EclFrameDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__EclFrameDictLN_MultilineWidget.tagnum = -1 ;
  G__EclFrameDictLN_vectorlETGLabelmUcOallocatorlETGLabelmUgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlETGLabelmUcOallocatorlETGLabelmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_EclPainter.tagnum = -1 ;
  G__EclFrameDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_EclPainterType.tagnum = -1 ;
  G__EclFrameDictLN_vectorlETGLPlanecOallocatorlETGLPlanegRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlETGLPlanecOallocatorlETGLPlanegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_pairlEboolcOTGLLine3gR.tagnum = -1 ;
  G__EclFrameDictLN_pairlEboolcOTGLVertex3gR.tagnum = -1 ;
  G__EclFrameDictLN_listlETGLOverlayElementmUcOallocatorlETGLOverlayElementmUgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_listlETGLSceneInfomUcOallocatorlETGLSceneInfomUgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_vectorlETGLSceneInfomUcOallocatorlETGLSceneInfomUgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlETGLSceneInfomUcOallocatorlETGLSceneInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_vectorlETGLOverlayElementmUcOallocatorlETGLOverlayElementmUgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlETGLOverlayElementmUcOallocatorlETGLOverlayElementmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_listlETGLColorSetmUcOallocatorlETGLColorSetmUgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_TGLSAViewer.tagnum = -1 ;
  G__EclFrameDictLN_EclFrame.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableEclFrameDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGVerticalFrame);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGGroupFrame);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGCheckButton);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGDoubleHSlider);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGNumberEntry);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGListTreeItem);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGListTree);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_pairlEintcOintgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_pairlEdoublecOdoublegR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_EclData);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_MultilineWidget);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlETGLabelmUcOallocatorlETGLabelmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGLabelmUcOallocatorlETGLabelmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_EclPainter);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_EclPainterType);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlETGLPlanecOallocatorlETGLPlanegRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGLPlanecOallocatorlETGLPlanegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_pairlEboolcOTGLLine3gR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_pairlEboolcOTGLVertex3gR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_listlETGLOverlayElementmUcOallocatorlETGLOverlayElementmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_listlETGLSceneInfomUcOallocatorlETGLSceneInfomUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlETGLSceneInfomUcOallocatorlETGLSceneInfomUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGLSceneInfomUcOallocatorlETGLSceneInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlETGLOverlayElementmUcOallocatorlETGLOverlayElementmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGLOverlayElementmUcOallocatorlETGLOverlayElementmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_listlETGLColorSetmUcOallocatorlETGLColorSetmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGLSAViewer);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EclFrameDictLN_EclFrame),sizeof(EclFrame),-1,62464,(char*)NULL,G__setup_memvarEclFrame,G__setup_memfuncEclFrame);
}
extern "C" void G__cpp_setupEclFrameDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupEclFrameDict()");
  G__set_cpp_environmentEclFrameDict();
  G__cpp_setup_tagtableEclFrameDict();

  G__cpp_setup_inheritanceEclFrameDict();

  G__cpp_setup_typetableEclFrameDict();

  G__cpp_setup_memvarEclFrameDict();

  G__cpp_setup_memfuncEclFrameDict();
  G__cpp_setup_globalEclFrameDict();
  G__cpp_setup_funcEclFrameDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncEclFrameDict();
  return;
}
class G__cpp_setup_initEclFrameDict {
  public:
    G__cpp_setup_initEclFrameDict() { G__add_setup_func("EclFrameDict",(G__incsetup)(&G__cpp_setupEclFrameDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initEclFrameDict() { G__remove_setup_func("EclFrameDict"); }
};
G__cpp_setup_initEclFrameDict G__cpp_setup_initializerEclFrameDict;

