//
// File generated by rootcint at Thu Jun 22 18:28:12 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME EclFrameDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "EclFrameDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void Belle2cLcLEclFrame_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_Belle2cLcLEclFrame(void *p);
   static void deleteArray_Belle2cLcLEclFrame(void *p);
   static void destruct_Belle2cLcLEclFrame(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Belle2::EclFrame*)
   {
      ::Belle2::EclFrame *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Belle2::EclFrame >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Belle2::EclFrame", ::Belle2::EclFrame::Class_Version(), "./EclFrame.h", 50,
                  typeid(::Belle2::EclFrame), DefineBehavior(ptr, ptr),
                  &::Belle2::EclFrame::Dictionary, isa_proxy, 4,
                  sizeof(::Belle2::EclFrame) );
      instance.SetDelete(&delete_Belle2cLcLEclFrame);
      instance.SetDeleteArray(&deleteArray_Belle2cLcLEclFrame);
      instance.SetDestructor(&destruct_Belle2cLcLEclFrame);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Belle2::EclFrame*)
   {
      return GenerateInitInstanceLocal((::Belle2::EclFrame*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Belle2::EclFrame*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

      namespace Belle2 {
//______________________________________________________________________________
atomic_TClass_ptr EclFrame::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *EclFrame::Class_Name()
{
   return "Belle2::EclFrame";
}

//______________________________________________________________________________
const char *EclFrame::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Belle2::EclFrame*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int EclFrame::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Belle2::EclFrame*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void EclFrame::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Belle2::EclFrame*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *EclFrame::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Belle2::EclFrame*)0x0)->GetClass();} }
   return fgIsA;
}

} // namespace Belle2
      namespace Belle2 {
//______________________________________________________________________________
void EclFrame::Streamer(TBuffer &R__b)
{
   // Stream an object of class Belle2::EclFrame.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(Belle2::EclFrame::Class(),this);
   } else {
      R__b.WriteClassBuffer(Belle2::EclFrame::Class(),this);
   }
}

} // namespace Belle2
//______________________________________________________________________________
      namespace Belle2 {
void EclFrame::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class Belle2::EclFrame.
      TClass *R__cl = ::Belle2::EclFrame::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_settings", &m_settings);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_frame1", &m_frame1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_frame2", &m_frame2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_frame3", &m_frame3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_list_tree", &m_list_tree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_frame4", &m_frame4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_frame5", &m_frame5);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_draw", &m_draw);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_draw_all", &m_draw_all);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_ecanvas", &m_ecanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_painter_type", &m_painter_type);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_ecl_data", &m_ecl_data);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_time_slider", &m_time_slider);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_ev_slider", &m_ev_slider);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_events_min", &m_events_min);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_events_max", &m_events_max);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_channel_id", &m_channel_id);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_subsys", &m_subsys);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_min_en_threshold", &m_min_en_threshold);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_max_en_threshold", &m_max_en_threshold);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_threshold_switch", &m_threshold_switch);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_ecl_painter", &m_ecl_painter);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_mapper", &m_mapper);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_auto_display", &m_auto_display);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_last_event", &m_last_event);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_open", &m_open);
      TGMainFrame::ShowMembers(R__insp);
}

} // namespace Belle2
namespace ROOT {
   // Wrapper around operator delete
   static void delete_Belle2cLcLEclFrame(void *p) {
      delete ((::Belle2::EclFrame*)p);
   }
   static void deleteArray_Belle2cLcLEclFrame(void *p) {
      delete [] ((::Belle2::EclFrame*)p);
   }
   static void destruct_Belle2cLcLEclFrame(void *p) {
      typedef ::Belle2::EclFrame current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::Belle2::EclFrame

/********************************************************
* EclFrameDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableEclFrameDict();

extern "C" void G__set_cpp_environmentEclFrameDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("EclFrame.h");
  G__cpp_reset_tagtableEclFrameDict();
}
#include <new>
extern "C" int G__cpp_dllrevEclFrameDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Belle2::EclFrame */
static int G__EclFrameDict_950_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Belle2::EclFrame* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 4
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new Belle2::EclFrame(
(int) G__int(libp->para[0]), (Belle2::EclData*) G__int(libp->para[1])
, (bool) G__int(libp->para[2]), (Belle2::ECLChannelMapper*) G__int(libp->para[3]));
   } else {
     p = new((void*) gvp) Belle2::EclFrame(
(int) G__int(libp->para[0]), (Belle2::EclData*) G__int(libp->para[1])
, (bool) G__int(libp->para[2]), (Belle2::ECLChannelMapper*) G__int(libp->para[3]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFrame));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Belle2::EclFrame*) G__getstructoffset())->loadNewData();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Belle2::EclFrame*) G__getstructoffset())->updateCanvas();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Belle2::EclFrame*) G__getstructoffset())->handleMenu((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Belle2::EclFrame*) G__getstructoffset())->updateEventRange();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Belle2::EclFrame*) G__getstructoffset())->showPrevEvents();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Belle2::EclFrame*) G__getstructoffset())->showNextEvents();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Belle2::EclFrame*) G__getstructoffset())->excludeChannel();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Belle2::EclFrame*) G__getstructoffset())->doDraw();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Belle2::EclFrame*) G__getstructoffset())->doDrawAll();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Belle2::EclFrame*) G__getstructoffset())->updateInfo((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (TObject*) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Belle2::EclFrame*) G__getstructoffset())->changeRange((TGListTreeItem*) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((Belle2::EclFrame*) G__getstructoffset())->changeType((int) G__int(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((Belle2::EclFrame*) G__getstructoffset())->changeType((int) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Belle2::EclFrame::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Belle2::EclFrame::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Belle2::EclFrame::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Belle2::EclFrame::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Belle2::EclFrame*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Belle2::EclFrame::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Belle2::EclFrame::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Belle2::EclFrame::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EclFrameDict_950_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Belle2::EclFrame::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Belle2::EclFrame G__TBelle2cLcLEclFrame;
static int G__EclFrameDict_950_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Belle2::EclFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Belle2::EclFrame*) (soff+(sizeof(Belle2::EclFrame)*i)))->~G__TBelle2cLcLEclFrame();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Belle2::EclFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Belle2::EclFrame*) (soff))->~G__TBelle2cLcLEclFrame();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Belle2::EclFrame */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncEclFrameDict {
 public:
  G__Sizep2memfuncEclFrameDict(): p(&G__Sizep2memfuncEclFrameDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncEclFrameDict::*p)();
};

size_t G__get_sizep2memfuncEclFrameDict()
{
  G__Sizep2memfuncEclFrameDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceEclFrameDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFrame))) {
     Belle2::EclFrame *G__Lderived;
     G__Lderived=(Belle2::EclFrame*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFrame),G__get_linked_tagnum(&G__EclFrameDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFrame),G__get_linked_tagnum(&G__EclFrameDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFrame),G__get_linked_tagnum(&G__EclFrameDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFrame),G__get_linked_tagnum(&G__EclFrameDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFrame),G__get_linked_tagnum(&G__EclFrameDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFrame),G__get_linked_tagnum(&G__EclFrameDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFrame),G__get_linked_tagnum(&G__EclFrameDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableEclFrameDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Int_t,TGeoElementRN*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGeoElementRN*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGeoElementRN*,less<int> >",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ThreadData_t*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGeoVolumeAssembly::ThreadData_t*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__EclFrameDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGLabel*>",117,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGLabelmUcOallocatorlETGLabelmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGLabelmUcOallocatorlETGLabelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGLabelmUcOallocatorlETGLabelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGLabelmUcOallocatorlETGLabelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EclFrameDictLN_vectorlETGLabelmUcOallocatorlETGLabelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__EclFrameDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Belle2::EclFrame */
static void G__setup_memvarBelle2cLcLEclFrame(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFrame));
   { Belle2::EclFrame *p; p=(Belle2::EclFrame*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGVerticalFrame),-1,-1,4,"m_settings=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLMultilineWidget),-1,-1,4,"m_frame1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGGroupFrame),-1,-1,4,"m_frame2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGGroupFrame),-1,-1,4,"m_frame3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGListTree),-1,-1,4,"m_list_tree=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGGroupFrame),-1,-1,4,"m_frame4=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGGroupFrame),-1,-1,4,"m_frame5=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGTextButton),-1,-1,4,"m_draw=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGTextButton),-1,-1,4,"m_draw_all=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TRootEmbeddedCanvas),-1,-1,4,"m_ecanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclPainterType),-1,-1,4,"m_painter_type=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclData),-1,-1,4,"m_ecl_data=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGDoubleHSlider),-1,-1,4,"m_time_slider=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGDoubleHSlider),-1,-1,4,"m_ev_slider=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGNumberEntry),-1,-1,4,"m_events_min=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGNumberEntry),-1,-1,4,"m_events_max=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGNumberEntry),-1,-1,4,"m_channel_id=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclDatacLcLEclSubsystem),-1,-1,4,"m_subsys=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGNumberEntry),-1,-1,4,"m_min_en_threshold=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGNumberEntry),-1,-1,4,"m_max_en_threshold=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TGCheckButton),-1,-1,4,"m_threshold_switch=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclPainter),-1,-1,4,"m_ecl_painter=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLECLChannelMapper),-1,-1,4,"m_mapper=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_auto_display=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"m_last_event=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_open=",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFramecLcLEclFrameCommandIdentifiers),-1,-2,4,"M_FILE_SAVE=0LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFramecLcLEclFrameCommandIdentifiers),-1,-2,4,"M_FILE_EXIT=1LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFramecLcLEclFrameCommandIdentifiers),-1,-2,4,"M_VIEW_EVENTS=2LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFramecLcLEclFrameCommandIdentifiers),-1,-2,4,"M_VIEW_ENERGY=3LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFramecLcLEclFrameCommandIdentifiers),-1,-2,4,"M_VIEW_DET_FULL=4LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFramecLcLEclFrameCommandIdentifiers),-1,-2,4,"M_VIEW_DET_FORW=5LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFramecLcLEclFrameCommandIdentifiers),-1,-2,4,"M_VIEW_DET_BACK=6LL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFramecLcLEclFrameCommandIdentifiers),-1,-2,4,"M_VIEW_DET_BARR=7LL",0,(char*)NULL);
   G__memvar_setup((void*)0,67,0,1,-1,-1,-2,4,"filetypes[]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EclFrameDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarEclFrameDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBelle2cLcLEclFrame(void) {
   /* Belle2::EclFrame */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFrame));
   G__memfunc_setup("EclFrame",767,G__EclFrameDict_950_0_1, 105, G__get_linked_tagnum(&G__EclFrameDictLN_Belle2cLcLEclFrame), -1, 0, 4, 1, 1, 0, 
"i - - 0 - painter_type U 'Belle2::EclData' - 0 - data "
"g - - 0 - auto_display U 'Belle2::ECLChannelMapper' - 0 - mapper", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("loadNewData",1092,G__EclFrameDict_950_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("updateCanvas",1247,G__EclFrameDict_950_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("initGUI",665,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 4, 0, 
"i - - 0 - w i - - 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("initData",814,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("handleMenu",1025,G__EclFrameDict_950_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("updateEventRange",1650,G__EclFrameDict_950_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("showPrevEvents",1491,G__EclFrameDict_950_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("showNextEvents",1493,G__EclFrameDict_950_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("excludeChannel",1443,G__EclFrameDict_950_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("doDraw",609,G__EclFrameDict_950_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("doDrawAll",890,G__EclFrameDict_950_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("updateInfo",1039,G__EclFrameDict_950_0_13, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - event i - - 0 - px "
"i - - 0 - py U 'TObject' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("changeRange",1107,G__EclFrameDict_950_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TGListTreeItem' - 0 - entry i - - 0 - btn", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("changeType",1032,G__EclFrameDict_950_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - type g - - 0 'true' redraw", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__EclFrameDict_950_0_16, 85, G__get_linked_tagnum(&G__EclFrameDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Belle2::EclFrame::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__EclFrameDict_950_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Belle2::EclFrame::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__EclFrameDict_950_0_18, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Belle2::EclFrame::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__EclFrameDict_950_0_19, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Belle2::EclFrame::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__EclFrameDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__EclFrameDict_950_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__EclFrameDict_950_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Belle2::EclFrame::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__EclFrameDict_950_0_25, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Belle2::EclFrame::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__EclFrameDict_950_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Belle2::EclFrame::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__EclFrameDict_950_0_27, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Belle2::EclFrame::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~EclFrame", 893, G__EclFrameDict_950_0_28, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncEclFrameDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
}

static void G__cpp_setup_global9() {
}

static void G__cpp_setup_global10() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalEclFrameDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
  G__cpp_setup_global9();
  G__cpp_setup_global10();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcEclFrameDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__EclFrameDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGVerticalFrame = { "TGVerticalFrame" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGGroupFrame = { "TGGroupFrame" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGCheckButton = { "TGCheckButton" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGDoubleHSlider = { "TGDoubleHSlider" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGNumberEntry = { "TGNumberEntry" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGListTreeItem = { "TGListTreeItem" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TGListTree = { "TGListTree" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR = { "map<int,TGeoElementRN*,less<int>,allocator<pair<const int,TGeoElementRN*> > >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR = { "vector<TGeoVolumeAssembly::ThreadData_t*,allocator<TGeoVolumeAssembly::ThreadData_t*> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGeoVolumeAssembly::ThreadData_t*,allocator<TGeoVolumeAssembly::ThreadData_t*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_Belle2 = { "Belle2" , 110 , -1 };
G__linked_taginfo G__EclFrameDictLN_Belle2cLcLECLChannelMapper = { "Belle2::ECLChannelMapper" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_Belle2cLcLEclData = { "Belle2::EclData" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_Belle2cLcLEclDatacLcLEclSubsystem = { "Belle2::EclData::EclSubsystem" , 101 , -1 };
G__linked_taginfo G__EclFrameDictLN_Belle2cLcLMultilineWidget = { "Belle2::MultilineWidget" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_vectorlETGLabelmUcOallocatorlETGLabelmUgRsPgR = { "vector<TGLabel*,allocator<TGLabel*> >" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_reverse_iteratorlEvectorlETGLabelmUcOallocatorlETGLabelmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGLabel*,allocator<TGLabel*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_Belle2cLcLEclPainter = { "Belle2::EclPainter" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_Belle2cLcLEclPainterType = { "Belle2::EclPainterType" , 101 , -1 };
G__linked_taginfo G__EclFrameDictLN_Belle2cLcLEclFrame = { "Belle2::EclFrame" , 99 , -1 };
G__linked_taginfo G__EclFrameDictLN_Belle2cLcLEclFramecLcLEclFrameCommandIdentifiers = { "Belle2::EclFrame::EclFrameCommandIdentifiers" , 101 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableEclFrameDict() {
  G__EclFrameDictLN_TClass.tagnum = -1 ;
  G__EclFrameDictLN_TBuffer.tagnum = -1 ;
  G__EclFrameDictLN_TMemberInspector.tagnum = -1 ;
  G__EclFrameDictLN_TObject.tagnum = -1 ;
  G__EclFrameDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_TQObject.tagnum = -1 ;
  G__EclFrameDictLN_TGWindow.tagnum = -1 ;
  G__EclFrameDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_TGObject.tagnum = -1 ;
  G__EclFrameDictLN_TGFrame.tagnum = -1 ;
  G__EclFrameDictLN_TGCompositeFrame.tagnum = -1 ;
  G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__EclFrameDictLN_TGTextButton.tagnum = -1 ;
  G__EclFrameDictLN_TGVerticalFrame.tagnum = -1 ;
  G__EclFrameDictLN_TGMainFrame.tagnum = -1 ;
  G__EclFrameDictLN_TGGroupFrame.tagnum = -1 ;
  G__EclFrameDictLN_TGCheckButton.tagnum = -1 ;
  G__EclFrameDictLN_TGDoubleHSlider.tagnum = -1 ;
  G__EclFrameDictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__EclFrameDictLN_TGNumberEntry.tagnum = -1 ;
  G__EclFrameDictLN_TGListTreeItem.tagnum = -1 ;
  G__EclFrameDictLN_TGListTree.tagnum = -1 ;
  G__EclFrameDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_Belle2.tagnum = -1 ;
  G__EclFrameDictLN_Belle2cLcLECLChannelMapper.tagnum = -1 ;
  G__EclFrameDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__EclFrameDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__EclFrameDictLN_Belle2cLcLEclData.tagnum = -1 ;
  G__EclFrameDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_Belle2cLcLEclDatacLcLEclSubsystem.tagnum = -1 ;
  G__EclFrameDictLN_Belle2cLcLMultilineWidget.tagnum = -1 ;
  G__EclFrameDictLN_vectorlETGLabelmUcOallocatorlETGLabelmUgRsPgR.tagnum = -1 ;
  G__EclFrameDictLN_reverse_iteratorlEvectorlETGLabelmUcOallocatorlETGLabelmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EclFrameDictLN_Belle2cLcLEclPainter.tagnum = -1 ;
  G__EclFrameDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__EclFrameDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__EclFrameDictLN_Belle2cLcLEclPainterType.tagnum = -1 ;
  G__EclFrameDictLN_Belle2cLcLEclFrame.tagnum = -1 ;
  G__EclFrameDictLN_Belle2cLcLEclFramecLcLEclFrameCommandIdentifiers.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableEclFrameDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGVerticalFrame);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGGroupFrame);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGCheckButton);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGDoubleHSlider);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGNumberEntry);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGListTreeItem);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TGListTree);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_Belle2);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_Belle2cLcLECLChannelMapper);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_Belle2cLcLEclData);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_Belle2cLcLEclDatacLcLEclSubsystem);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_Belle2cLcLMultilineWidget);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_vectorlETGLabelmUcOallocatorlETGLabelmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_reverse_iteratorlEvectorlETGLabelmUcOallocatorlETGLabelmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_Belle2cLcLEclPainter);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_Belle2cLcLEclPainterType);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EclFrameDictLN_Belle2cLcLEclFrame),sizeof(Belle2::EclFrame),-1,324608,(char*)NULL,G__setup_memvarBelle2cLcLEclFrame,G__setup_memfuncBelle2cLcLEclFrame);
   G__get_linked_tagnum_fwd(&G__EclFrameDictLN_Belle2cLcLEclFramecLcLEclFrameCommandIdentifiers);
}
extern "C" void G__cpp_setupEclFrameDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupEclFrameDict()");
  G__set_cpp_environmentEclFrameDict();
  G__cpp_setup_tagtableEclFrameDict();

  G__cpp_setup_inheritanceEclFrameDict();

  G__cpp_setup_typetableEclFrameDict();

  G__cpp_setup_memvarEclFrameDict();

  G__cpp_setup_memfuncEclFrameDict();
  G__cpp_setup_globalEclFrameDict();
  G__cpp_setup_funcEclFrameDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncEclFrameDict();
  return;
}
class G__cpp_setup_initEclFrameDict {
  public:
    G__cpp_setup_initEclFrameDict() { G__add_setup_func("EclFrameDict",(G__incsetup)(&G__cpp_setupEclFrameDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initEclFrameDict() { G__remove_setup_func("EclFrameDict"); }
};
G__cpp_setup_initEclFrameDict G__cpp_setup_initializerEclFrameDict;

